[colors.bright]
black = "#000000"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#000000"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#ED5F74"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#000000"
foreground = "#B3B1AD"
