[window]
width = 1280
height = 1024
opacity = 0.85
blur = true
decorations = "enabled"

[editor]
program = "nvim"
args = []

[shell]
program = "nu"
args = []

[fonts]
family = "Iosevka NF"
size = 18
#disable-warning-not-found = false

