[pueue.files]
pueue = "~/.config/pueue"

[yazi.files]
yazi = "~/.config/yazi"

[nushell.files]
nushell = "~/.config/nushell"

[vim.files]
nvim = "~/.config/nvim"

[shell.files]
git = "~/.gitconfig"

[fish.files]
fish = "~/.config/fish"

