[pueue.files]
pueue = "~/.config/pueue"

[yazi.files]
yazi = "~/.config/yazi"

[nushell.files]
nushell = "~/.config/nushell"

[vim.files]
nvim = "~/.config/nvim"

[gitconfig.files]
git = "~/.gitconfig"

[fish.files]
fish = "~/.config/fish"

[alacritty.files]
alacritty = "~/.config/alacritty"

[zellij.files]
zellij = "~/.config/zellij"

[tmux.files]
tmux = "~/.tmux.conf"

[wezterm.files]
wezterm = "~/.wezterm.lua"

[starship.files]
starship = "~/.config/starship.toml"

[idea.files]
ideavimrc = "~/.ideavimrc"
vimrc = "~/.vimrc"
