[pueue.files]
pueue = "~/.config/pueue"

[yazi.files]
yazi = "~/.config/yazi"

[nushell.files]
nushell = "~/.config/nushell"

[vim.files]
nvim = "~/.config/nvim"

[gitconfig.files]
git = "~/.gitconfig"

[fish.files]
fish = "~/.config/fish"

[alacritty.files]
alacritty = "~/.config/alacritty"

[rio.files]
rio = "~/.config/rio"

[zellij.files]
zellij = "~/.config/zellij"

[tmux.files]
tmux = "~/.tmux.conf"

[wezterm.files]
wezterm = "~/.wezterm.lua"

[starship.files]
starship = "~/.config/starship.toml"

[idea.files]
ideavimrc = "~/.ideavimrc"
vimrc = "~/.vimrc"

[bspwm.files]
bspwm = "~/.config/bspwm"

[sxhkd.files]
sxhkd = "~/.config/sxhkd"

[rofi.files]
rofi = "~/.config/rofi"

[polybar.files]
polybar = "~/.config/polybar"

[hypr.files]
hypr = "~/.config/hypr"

[kitty.files]
kitty = "~/.config/kitty"

[i3.files]
i3 = "~/.config/i3"

[dunst.files]
dunst = "~/.config/dunst"

[niri.files]
niri = "~/.config/niri"

[helix.files]
helix = "~/.config/helix"

[waybar.files]
waybar = "~/.config/waybar"
